config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tickets do
    resources :ticket_replies
  end
  resources :user_types
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'password_changes', to: 'password_changes#edit', as: 'password_changes'
  post 'password_changes', to: 'password_changes#update'

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'reports', to: 'dashboard#reports', as: 'reports'
  get 'welcome', to: 'dashboard#welcome', as: 'welcome'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'registrations', to: 'users#registration', as: 'registrations'
  post 'registrations', to: 'users#create'

  get 'show_tickets/:id', to: 'tickets#show_tickets', as: 'show_tickets'

  root 'dashboard#home'
  ## for API

  mount Users::TypesAPI => '/api/user_types'
  mount Users::UsersAPI => '/api/users'
  mount Tickets::TicketsAPI =>'/api/tickets'
end

app/views/layouts/admin/_footer.html.erb
<footer class="main-footer no-print">
  <div class="pull-right hidden-xs">
    <b>Version</b> 1.0.0
  </div>
  <strong>Copyright &copy; <%= Time.now.year %> <a href="tanbir.cf" target="_blank">hmtanbir</a>.</strong> All rights reserved.
</footer>

app/views/layouts/admin/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title><%= full_title(title) %></title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

app/views/layouts/admin/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="javascript:void(0)" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">      
      <b><i class="fa fa-diamond"></i></b>    
    </span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">    
      <b>Tickets</b>&nbsp;Management      
    </span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="javascript:void(0)" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
            <%# if current_user.image.present? %>
              <%#= image_tag current_user.image.url(:medium), class: 'user-image' %>
            <%# else %>
              <i class="fa fa-user"></i>
            <%# end %>
            <span class="hidden-xs"><%= current_user.name %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <%# if current_user.image.present? %>
                <%#= image_tag current_user.image.url(:large), class: 'img-circle' %>
              <%# end %>
              <p>
                <%= current_user.name %> - <%= current_user.profession %>
                <small>Member since <%= current_user.created_at.strftime('%b %d, %Y') %></small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="row">
                <div class="col-xs-12 text-center">
                  <a href="javascript:void(0)"><%= current_user.user_type.name.upcase %></a>
                </div>
              </div>
              <!-- /.row -->
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="<%= user_url(current_user) %>" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="<%= logout_url %>" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/admin/_nav.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <% if current_user.image.present?  %>
          <%= image_tag current_user.image.url(:medium), class: 'img-circle' %>
        <% else %>
          <i class="fa fa-user fa-3x"></i>
        <% end %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.name %></p>        
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li class="#">
        <a href="<%= dashboard_url %>">
          <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        </a>
      </li>

      <li class="treeview <%= 'hidden' unless (has_permission?('user') || has_permission?('usertype')) %>">
        <a href="javascript:void(0)">
          <i class="fa fa-gears"></i>
          <span>Administration</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li class="<%= 'hidden' unless has_permission?('user') %>"><a href="<%= users_url %>"><i class="fa fa-circle-o"></i> Manage Users</a></li>
          <li class="<%= 'hidden' unless has_permission?('usertype') %>"><a href="<%= user_types_url %>"><i class="fa fa-circle-o"></i> User Type</a></li>
        </ul>
      </li>

      <li>
        <a href="<%= password_changes_url %>">
          <i class="fa fa-key"></i> <span>Change Password</span>
        </a>
      </li>

      <li>
        <a class="<%= 'hidden' unless has_permission?('ticket') %>" href="<%= tickets_url %>">
          <i class="fa fa-book"></i> <span>Tickets</span>
        </a>
      </li>

      <li>
        <a class="<%= 'hidden' unless has_permission?('dashboard') %>" href="<%= reports_url %>">
          <i class="fa fa-wpforms"></i> <span>Reports</span>
        </a>
      </li>

    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin/_page_header.html.erb
<section class="content-header">
  <h1>
    <%= title %>
    <small>Preview</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="javascript:void(0)"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><%= breadcrumb %></li>
  </ol>
</section>

app/views/layouts/admin/main.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/admin/head', title: @title %>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  <%= render 'layouts/admin/header' %>
  <!-- Left side column. contains the logo and sidebar -->
  <%= render 'layouts/admin/nav' %>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <%= render 'layouts/admin/page_header', title: @title, breadcrumb: @breadcrumb %>
    <!-- Main content -->
    <section class="content">
      <%= render 'shared/flash_notice' %>
      <%= yield %>
    </section>
    <!-- /.content -->
    <div class="clearfix"></div>
  </div>
  <!-- /.content-wrapper -->
  <%= render 'layouts/admin/footer' %>

</div>
<!-- ./wrapper -->
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>