config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tickets do
    resources :ticket_replies
  end
  resources :user_types
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'password_changes', to: 'password_changes#edit', as: 'password_changes'
  post 'password_changes', to: 'password_changes#update'

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'reports', to: 'dashboard#reports', as: 'reports'
  get 'welcome', to: 'dashboard#welcome', as: 'welcome'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'registrations', to: 'users#registration', as: 'registrations'
  post 'registrations', to: 'users#create'

  get 'show_tickets/:id', to: 'tickets#show_tickets', as: 'show_tickets'

  root 'dashboard#home'
  ## for API

  mount Users::TypesAPI => '/api/user_types'
  mount Users::UsersAPI => '/api/users'
  mount Tickets::TicketsAPI =>'/api/tickets'
end

app/models/user.rb
class User < ApplicationRecord  
  has_attached_file :image, styles: { large: '200x200>',
                                      medium: '160x160>',
                                      thumb: '100x100>' }, default_url: '/assets/no-user.png'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  belongs_to :user_type, class_name: 'UserType', inverse_of: 'users'
  has_many :tickets, class_name: 'Ticket', inverse_of: 'user', dependent: :destroy
  delegate :name, to: :user_type, prefix: true

  attr_accessor :remember_token
  
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :username, uniqueness: true, presence: true, length: { maximum: 50 }
  validates :profession, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :update, allow_blank: true

  # scope for agents count
  # User.agents_count
  scope :agents_count, -> {
    where(user_type_id: UserType.find_by(name: 'agent').id).count
  }

  # scope for customer count
  # User.customers_count
  scope :customers_count, -> {
    where(user_type_id: UserType.find_by(name: 'customer').id).count
  }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/user_type.rb
class UserType < ApplicationRecord
  has_many :users, class_name: 'User', inverse_of: 'user_type', dependent: :destroy

  has_one :permission, class_name: 'Permission', inverse_of: 'user_type', foreign_key: 'user_type_id', dependent: :destroy
  accepts_nested_attributes_for :permission
  validates_presence_of :name
  validates_uniqueness_of :name

  delegate :dashboard, :usertype, :user,
           :add, :edit,:remove_ability, to: :permission, prefix: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorized?, except: [:registration, :create]
  before_action :user_permission, only: [:index]

  before_action :edit_ability?, only: [:edit, :update]
  before_action :can_delete?, only: :destroy

  layout 'admin/main', except: :registration

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @title = 'Users Management'
    @breadcrumb = 'Users'
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @title = 'Users Management'
    @breadcrumb = 'Users > Show'
  end

  # GET /users/new
  def new
    @title = 'Users Management'
    @breadcrumb = 'Users > New'
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @title = 'Users Management'
    @breadcrumb = 'Users > Edit'
  end

  # POST /users
  # POST /users.json
  def create
    @title = 'Users Management'
    @breadcrumb = 'Users > New'
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html {
          if @user.user_type.name == 'customer'
            redirect_to login_url, notice: 'Registration is completed. Please login'
          else
            redirect_to @user, notice: 'User was successfully created.'
          end
        }
        format.json { render :show, status: :created, location: @user }
      else
        format.html {
          if @user.user_type.name == 'customer'
            redirect_to registrations_path, alert: @user.errors.full_messages.to_sentence
          else
            redirect_to new_user_path, alert: @user.errors.full_messages.to_sentence
          end
        }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @title = 'Users Management'
    @breadcrumb = 'Users > Edit'
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /users/registration
  def registration
    @user = User.new
    @type_id = UserType.find_by(name: 'customer', published: true).id
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def user_permission
    has_controller_permission?('user')
  end

  def set_user
    @user = User.find(params[:id])
  end

  def match_user?
    user= User.find_by_id(current_user.id)
    user.id == set_user.id
  end

  def edit_ability?
    unless match_user? || has_permission?('edit')
      redirect_to users_path, notice: "You don't have permission!"
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation, :email, :ip_address,
                                 :published, :user_type_id, :profession, :image, :phone)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Logs in the given user.
  def log_in(user)    
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    current_user.present?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)    
    @current_user = nil
  end

  ## before_action :authorized?, except: :index
  def authorized?
    if current_user.nil?
      redirect_to login_url, notice: 'You have to login at first'
    end
  end

  def self.ip_address
    Socket.ip_address_list.detect(&:ipv4_private?).try(:ip_address)
  end
end

app/views/users/_form.html.erb
<div class="row">
  <!-- left column -->
  <div class="col-md-12 col-xs-12">
    <!-- general form elements -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">
          <% if  request.original_url == new_user_url %>
          <%= 'New User' %>
           <% else %>
          <%= 'Editing User' %>
          <% end %>
        </h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->      
          <%= form_with(model: user, local: true) do |f| %>
          <div class="box-body">
            <% if user.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
                  <ul>
                    <% user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <div class="col-md-4 col-xs-4">
              <% if user.image.present? %>
                  <%= image_tag user.image.url(:large), class: 'img-responsive' %>
              <% end %>

              <br/>

              <div class="form-group">
                <div class="btn btn-primary btn-file"> <i class="glyphicon glyphicon-folder-open"></i> &nbsp;Browse … <%= f.file_field :image %></div>
                <% if user.image.present? %>
                    <p class="help-block">Please upload another profile photo</p>
                <% else %>
                <p class="help-block">Please upload in your profile photo</p>
                <% end %>
              </div>

            </div>

            <div class="col-md-4 col-xs-4">
              <div class="form-group">
                <%= f.label :full_name %>*
                <%= f.text_field :name, required: 'require', class: 'form-control', placeholder: 'Name' %>
              </div>
              <div class="form-group">
                <label>User Type</label>*
                <select class="form-control" name="user[user_type_id]" id="user_user_type_id">
                  <% UserType.where(published: true).each do |type| %>
                      <option value="<%= type.id %>"><%= type.name.upcase %></option>
                  <% end %>
                </select>
              </div>

              <div class="form-group">
                <%= f.label :email %>*
                <%= f.email_field :email, required: 'require', class: 'form-control', placeholder: 'E-mail' %>
              </div>
              <div class="form-group">
                <%= f.label :profession %>
                <%= f.text_field :profession, required: 'require', class: 'form-control', placeholder: 'Profession' %>
              </div>

            </div>
            <div class="col-md-4 col-xs-4">
              <div class="form-group">
                <%= f.label :username %>*
                <%= f.text_field :username, required: 'require', class: 'form-control', placeholder: 'Username' %>
              </div>

              <div class="form-group">
                <%= f.label :password %>*
                <div class=" row">
                  <div class="col-xs-6">
                    <%= f.password_field :password, required: 'require', class: 'form-control', placeholder: 'Password' %>
                    <small class="help-block">Minimum 6 characters</small>
                  </div>

                  <div class="col-xs-6">
                    <%= f.password_field :password_confirmation, required: 'require', class: 'form-control', placeholder: 'Confirm' %>
                  </div>
                </div>

              </div>

              <div class="form-group">
                <div class="row">            

              <div class="col-xs-12 ">
                <%= f.label :mobile_number %>*
                <%= f.number_field :phone, required: 'require', class: 'form-control', placeholder: 'Mobile Number' %>
              </div>
                </div>
              </div>

              <div class="checkbox">
                <label>
                  <%= f.check_box :published %> Published me
                </label>
              </div>

            </div>
          </div>
          <!-- /.box-body -->
          <div class="modal-footer">
            <%= f.submit 'Submit', class: 'btn btn-primary' %>
            <%= link_to 'Back', users_path, class: 'btn btn-default' %>
          </div>
      <% end %>
      </div>
  <!-- /.box -->

</div>
</div>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-12 col-md-12">
    <div class="box">
      <div class="box-header">
        <div class=" col-md-6 col-xs-6">
          <h3 class="box-title">User List</h3>
        </div>
        <div class="col-md-6 col-xs-6" align="right">
          <a href="<%= new_user_url %>" class="btn btn-primary btn-sm <%= 'hidden' unless has_permission?('add') %>" ><i class="fa fa-plus-circle"></i> Add New</a>
          <a href="<%= user_types_url %>" class="btn btn-primary btn-sm <%= 'hidden' unless has_permission?('usertype') %>" ><i class="fa fa-users"></i> User Type</a>
        </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Username</th>
            <th>E-mail</th>
            <th>Published</th>            
            <th>Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.user_type_name.upcase %></td>
                <td><%= user.username %></td>
                <td><%= user.email.downcase %></td>
                <td><%= user.published %></td>                
                <td>
                  <a href="<%= edit_user_path(user) %>" class="btn btn-info btn-flat <%= 'hidden' unless has_permission?('edit') %>" ><i class="fa fa-pencil"></i></a>
                  <a href="<%= user_path(user) %>" class="btn btn-success btn-flat" ><i class="fa fa-eye"></i></a>
                  <a data-confirm="Are you sure?" class='btn btn-danger btn-flat <%= 'hidden' unless has_permission?('remove_ability') %>' rel="nofollow" data-method="delete" href="<%= user_path(user) %>"><i class="fa fa-trash-o"></i></a>
                </td>
              </tr>
          <% end %>
          </tbody>
          <tfoot>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Username</th>
            <th>E-mail</th>
            <th>Published</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
          </tfoot>
        </table>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
  <!-- /.col -->
</div>
<!-- /.row -->

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/registration.html.erb
<div class="container">
  <div class="jumbotron">
  <div class="row">
  <!-- left column -->
  <div class="col-md-12 col-xs-12">
    <!-- general form elements -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">
          Registration as a New User
        </h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <%= form_with(model: @user, local: true) do |f| %>
        <div class="box-body">
          <div class="col-md-6 col-xs-6">
            <div class="form-group">
              <%= f.label :full_name %>*
              <%= f.text_field :name, required: 'require', class: 'form-control', placeholder: 'Name' %>
            </div>

            <div class="form-group">
              <%= f.hidden_field :user_type_id, value: @type_id, id: 'user_type_id' %>
            </div>

            <div class="form-group">
              <%= f.label :email %>*
              <%= f.email_field :email, required: 'require', class: 'form-control', placeholder: 'E-mail' %>
            </div>

            <div class="form-group">
              <%= f.label :phone %>*
              <%= f.text_field :phone, required: 'require', class: 'form-control', placeholder: 'Phone' %>
            </div>

            <div class="form-group">
              <%= f.label :profession %>
              <%= f.text_field :profession, required: 'require', class: 'form-control', placeholder: 'Profession' %>
            </div>

          </div>

          <div class="col-md-6 col-xs-6">
            <div class="form-group">
              <%= f.label :username %>*
              <%= f.text_field :username, required: 'require', class: 'form-control', placeholder: 'Username' %>
            </div>

            <div class="form-group">
              <%= f.label :password %>*
              <div class=" row">
                <div class="col-xs-6">
                  <%= f.password_field :password, required: 'require', class: 'form-control', placeholder: 'Password' %>
                  <small class="help-block">Minimum 6 characters</small>
                </div>

                <div class="col-xs-6">
                  <%= f.password_field :password_confirmation, required: 'require', class: 'form-control', placeholder: 'Confirm' %>
                </div>
              </div>
           </div>



            <%= f.hidden_field :published, value: true %>

          </div>
        </div>
        <!-- /.box-body -->
        <div class="modal-footer">
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
          <%= link_to 'Back', users_path, class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
    <!-- /.box -->

  </div>
</div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <!-- left column -->
  <div class="col-md-12 col-xs-12">
    <!-- general form elements -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title"><%= @user.name%>'s Profile</h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <div class="box-body">

        <div class="col-md-4 col-xs-4">
          <div class="form-group">
            <%if @user.image.present? %>
              <%= image_tag @user.image.url(:large), class: 'img-responsive' %>
              <p class="help-block"><%= @user.name %>'s photo</p>
            <% else %>
              <%= 'No image is uploaded yet !' %>
            <% end %>
          </div>

        </div>

        <div class="col-md-4 col-xs-4">
          <div class="form-group">
            <label for="user_full_name">Full name</label>
            <span class="form-control"><%= @user.name %></span>
          </div>
          <div class="form-group">
            <label>User Type</label>
            <span class="form-control"><%= @user.user_type_name.upcase %></span>
          </div>

          <div class="form-group">
            <label for="user_email">Email</label>
            <span class="form-control" ><%= @user.email %></span>
          </div>       
        </div>

        <div class="col-md-4 col-xs-4">

          <div class="form-group">
            <label for="user_username">Username</label>
            <span class="form-control"><%= @user.username %></span>
          </div>          

          <div class="form-group">
            <label for="user_pin_number">Published</label>
            <span class="form-control"><%= @user.published %></span>
          </div> 

          <div class="form-group">
            <label for="user_profession">Profession</label>
            <span class="form-control"><%= @user.profession %></span>
          </div>        

        </div>
      </div>
      <!-- /.box-body -->
      <div class="modal-footer">
        <% if has_permission?('edit') %>
          <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' %>
        <% end %>
        <%= link_to 'Back', users_path, class: 'btn btn-default' %>
      </div>

    </div>
    <!-- /.box -->

  </div>
</div>