config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tickets do
    resources :ticket_replies
  end
  resources :user_types
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'password_changes', to: 'password_changes#edit', as: 'password_changes'
  post 'password_changes', to: 'password_changes#update'

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'reports', to: 'dashboard#reports', as: 'reports'
  get 'welcome', to: 'dashboard#welcome', as: 'welcome'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'registrations', to: 'users#registration', as: 'registrations'
  post 'registrations', to: 'users#create'

  get 'show_tickets/:id', to: 'tickets#show_tickets', as: 'show_tickets'

  root 'dashboard#home'
  ## for API

  mount Users::TypesAPI => '/api/user_types'
  mount Users::UsersAPI => '/api/users'
  mount Tickets::TicketsAPI =>'/api/tickets'
end

app/controllers/user_types_controller.rb
class UserTypesController < ApplicationController
  before_action :set_user_type, only: [:show, :edit, :update, :destroy]
  before_action :authorized?, :type_permission
  before_action :can_add?, only: [:new, :create]
  before_action :can_edit?, only: [:edit, :update]
  before_action :can_delete?, only: :destroy

  layout 'admin/main'

  # GET /user_types
  # GET /user_types.json
  def index
    @title = 'User Types Management'
    @breadcrumb = 'Users Types'
    @user_types = UserType.all
  end

  # GET /user_types/1
  # GET /user_types/1.json
  def show
    @title = 'User Types Management'
  end

  # GET /user_types/registration
  def new
    @title = 'User Types Management'
    @breadcrumb = 'Users Types > New'
    @user_type = UserType.new
    @user_type.build_permission
  end

  # GET /user_types/1/edit
  def edit
    @title = 'User Types Management'
    @breadcrumb = 'Users Types > Edit'
  end

  # POST /user_types
  # POST /user_types.json
  def create
    @title = 'User Types Management'
    @breadcrumb = 'Users Types > New'
    @user_type = UserType.new(user_type_params)

    respond_to do |format|
      if @user_type.save
        format.html { redirect_to @user_type, notice: 'User type was successfully created.' }
        format.json { render :show, status: :created, location: @user_type }
      else
        format.html { redirect_to new_user_type_path, alert: @user_type.errors.full_messages.to_sentence }
        format.json { render json: @user_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_types/1
  # PATCH/PUT /user_types/1.json
  def update
    @title = 'User Types Management'
    @breadcrumb = 'Users Types > Edit'
    respond_to do |format|
      if @user_type.update(user_type_params)
        format.html { redirect_to @user_type, notice: 'User type was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_type }
      else
        format.html { render :edit }
        format.json { render json: @user_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_types/1
  # DELETE /user_types/1.json
  def destroy
    @user_type.destroy
    respond_to do |format|
      format.html { redirect_to user_types_url, notice: 'User type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_type
      @user_type = UserType.find(params[:id])
    end

    def type_permission
      has_controller_permission?('usertype')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_type_params
      params.require(:user_type).permit(:name, :published,
                                        permission_attributes: [:dashboard, :usertype, :user, :ticket, :add, :edit, :remove_ability])
    end
end

app/views/user_types/_form.html.erb
  <div class="row">
  <!-- left column -->
  <div class="col-md-12 col-xs-12">
    <!-- general form elements -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">
          <% if  request.original_url == new_user_type_url %>
              <%= 'New User Type' %>
          <% else %>
              <%= 'Editing User Type' %>
          <% end %>
        </h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <%= form_with(model: user_type, local: true) do |f| %>
          <div class="box-body">            
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, required: 'require', class: 'form-control', placeholder: 'Name' %>
            </div>
            <label>Permissions</label>
            <%= f.fields_for :permission do |permission| %>
              <div class="checkbox">
                <label><%= permission.check_box :dashboard %>Dashboard</label>                
              </div>
              
              <label>Administrative Permission</label>
              <div class="checkbox">
                <label><%= permission.check_box :usertype %> User Types</label>
                <label><%= permission.check_box :user %>Users</label>
                <label><%= permission.check_box :ticket %>Tickets</label>
              </div>
              
              <label>Action Permission</label>
              <div class="checkbox">
                <label><%= permission.check_box :add %> Add</label>
                <label><%= permission.check_box :edit %>Edit</label>
                <label><%= permission.check_box :remove_ability %>Delete</label>
              </div>
            <% end %>

            <div class="checkbox">
              <label>
                <%= f.check_box :published %> Published me
              </label>
            </div>

          </div>
          <!-- /.box-body -->
          <div class="modal-footer">
            <%= f.submit 'Submit', class: 'btn btn-primary' %>
            <%= link_to 'Back', user_types_path, class: 'btn btn-default' %>
          </div>
      <% end %>
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/user_types/edit.html.erb
<%= render 'form', user_type: @user_type %>

app/views/user_types/index.html.erb
<div class="row">
  <div class="col-xs-12 col-md-12">
    <div class="box">
      <div class="box-header">
        <div class=" col-md-6 col-xs-6">
          <h3 class="box-title">User List</h3>
        </div>
        <div class="col-md-6 col-xs-6" align="right">
          <a href="<%= new_user_type_url %>" class="btn btn-primary btn-sm <%= 'hidden' unless has_permission?('add') %>" ><i class="fa fa-plus-circle"></i> Add New</a>
          <a href="<%= users_url %>" class="btn btn-primary btn-sm <%= 'hidden' unless has_permission?('user') %>" ><i class="fa fa-users"></i> Users</a>
        </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>Name</th>
            <th>Published</th>
            <th>Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @user_types.each do |type| %>
              <tr>
                <td><%= type.name %></td>
                <td><%= type.published %></td>
                <td>
                  <a href="<%= edit_user_type_path(type) %>" class="btn btn-info btn-flat <%= 'hidden' unless has_permission?('edit') %>" ><i class="fa fa-pencil"></i></a>
                  <a href="<%= user_type_path(type) %>" class="btn btn-success btn-flat" ><i class="fa fa-eye"></i></a>
                  <a data-confirm="Are you sure?" class='btn btn-danger btn-flat <%= 'hidden' unless has_permission?('remove_ability') %>' rel="nofollow" data-method="delete" href="<%= user_type_path(type) %>"><i class="fa fa-trash-o"></i></a>
                </td>
              </tr>
          <% end %>
          </tbody>
          <tfoot>
          <tr>
            <th>Name</th>
            <th>Published</th>
            <th>Actions</th>
          </tr>
          </tfoot>
        </table>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
  <!-- /.col -->
</div>
<!-- /.row -->

app/views/user_types/new.html.erb
<%= render 'form', user_type: @user_type %>

app/views/user_types/show.html.erb
<div class="row">
  <!-- left column -->
  <div class="col-md-12 col-xs-12">
    <!-- general form elements -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">User Type</h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <div class="box-body">
        <div class="form-group">
          <label for="user_full_name">Name</label>
          <span class="form-control"><%= @user_type.name %></span>
        </div>
        <div class="form-group">
          <label>Published</label>
          <span class="form-control"><%= @user_type.published %></span>
        </div>
      </div>
      <!-- /.box-body -->
      <div class="modal-footer">
        <% if has_permission?('edit')%>
        <%= link_to 'Edit', edit_user_type_path(@user_type), class: 'btn btn-primary' %>
        <% end %>
        <%= link_to 'Back', user_types_path, class: 'btn btn-default' %>
      </div>
    </div>
    <!-- /.box -->
  </div>
</div>