config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tickets do
    resources :ticket_replies
  end
  resources :user_types
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'password_changes', to: 'password_changes#edit', as: 'password_changes'
  post 'password_changes', to: 'password_changes#update'

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'reports', to: 'dashboard#reports', as: 'reports'
  get 'welcome', to: 'dashboard#welcome', as: 'welcome'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'registrations', to: 'users#registration', as: 'registrations'
  post 'registrations', to: 'users#create'

  get 'show_tickets/:id', to: 'tickets#show_tickets', as: 'show_tickets'

  root 'dashboard#home'
  ## for API

  mount Users::TypesAPI => '/api/user_types'
  mount Users::UsersAPI => '/api/users'
  mount Tickets::TicketsAPI =>'/api/tickets'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="javascript:void(0)">Supports</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_url %>">Home</a></li>
      <li><a href="<%= new_ticket_url %>">Add a Ticket</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><a href="<%= logout_url %>"><span class="glyphicon glyphicon-log-out"></span> Sign Out</a></li>
      <% else %>
        <li><a href="<%= registrations_url %>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="<%= new_session_url %>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(@title) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body class="hold-transition login-page">
<%= render 'layouts/nav'  %>
<%= render 'shared/flash_notice'  %>
<%= yield %>
<script>
</script>
</body>
</html>